name = "BeepBoopPack"
author = "LosBehinderos"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34d68e5b35c759e3394515a574c08d524fa552962abe4526c0041602d971af69"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
